services:
  auth-10-service:    
    container_name: collection-10-service
    build:
      context: .
      dockerfile: Dockerfile   
    env_file:
      - .env
    ports:
      - "5012:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_URL=${DATABASE_URL} 
    volumes:
      - ./dataprotection-keys:/home/app/.aspnet/DataProtection-Keys  
    networks:
      - tom-auth-net
      
networks:
  tom-auth-net:
    driver: bridge