name: .NET Core CI

on:
  push:
    branches: [ "main", "develop" ] # Ou mantenha ["**"] se quiser em todas
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest    

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x' # Verifique se seu projeto é 9 ou 10

    - name: Docker Run (Teste de Integração)
      run: |
        docker-compose up -d
      env:
        # Garante que o Docker Compose 'enxergue' a variável do sistema
        JwtSettings__Key: ${{ secrets.TOKEN_KEY }}
        
    - name: Restore dependencies
      # Boa prática: Usar caminhos sem o ./ inicial se estiver na raiz, mas ./src está correto
      run: dotnet restore src/Collection10Api.slnx

    - name: Build
      run: dotnet build src/Collection10Api.slnx --configuration Release --no-restore

    - name: Test
      run: dotnet test src/Collection10Api.slnx --configuration Release --no-build --verbosity normal