name: .NET Core CI

on:
  push:
    branches: [ "**" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest    

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x' 

    - name: Docker Run (Teste de Integração)
      run: |
        docker-compose up -d
      env:        
        JwtSettings__Key: ${{ secrets.TOKEN_KEY }}
        
    - name: Restore dependencies      
      run: dotnet restore src/Collection10Api.slnx

    - name: Build
      run: dotnet build src/Collection10Api.slnx --configuration Release --no-restore

    - name: Test
      run: dotnet test src/Collection10Api.slnx --configuration Release --no-build --verbosity normal